[book]
title = "LitMan 手册"
authors = ["Jingdong Zhang"]
language = "zh-CN"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
search.enable = true
