[package]
name = "litman-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Command-line interface for LitMan"

[[bin]]
name = "litman"
path = "src/main.rs"

[dependencies]
clap.workspace = true
litman-core = { path = "../litman-core" }
open.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
lopdf.workspace = true
tempfile.workspace = true
